# Generated by Django 6.1 on 2026-08-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='is_under_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
