# Generated by Django 6.1 on 2026-08-15 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('COMMITTED', 'Committed')], default='DRAFT', max_length=20)),
                ('fairness_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_allocations', to='allocations.allocationrun')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='hostels.bed')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='accounts.studentprofile')),
            ],
        ),
    ]
