# Generated by Django 6.1 on 2026-08-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrun',
            name='summary_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
